language: node_js
node_js:
  - 12
script:
  - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: 5f3cd158-5593-4eeb-a28d-6753dd9b10ad
  app: movie-testing
  on:
    repo: olacodes/movie-recomendation-testing